app = "bmb-trong-tai-so"
kill_signal = "SIGINT"
kill_timeout = "5s"
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  PHP_ENV = "production"

[deploy]
  release_command = ""

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[volumes]]
  name = "bmb_uploads"
  size = 1
  mount_point = "/var/www/html/uploads"
